flags=-g -Wall -Wextra -Werror -pedantic


2:
	gcc $(flags) ./2-linkedlist/lib-linked/*.c 2-linkedlist/2-linked_list.c ../_getpath.c ../1-strdup.c

3:
	gcc $(flags)  3-exec_cmd.c ../_getpath.c ../_exec_cmd.c ../_builtins_func.c

4:
	gcc $(flags)  4-*.c ../_puts.c ../_putchar.c

5:
	gcc $(flags)  5-p_func2.c ../_builtins_func.c

6:
	gcc $(flags)  6-*
